# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4418a7f04c6017ad4ba7612e977b3cd9e94f134fed460d12188aa55bcdd3171477385710f349830718631de19ddd40ed3243ae92d6b6017a815bbf99827a424a

test:
  secret_key_base: c1447fc214cb07e5bfa3ce504b63b8bbd268af6d2529544cb1e80b1a93df34789c84a6a039b51220ad6a7261e7c1aff927b6ece660f261b093761804f94f690e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
