#---the killers
    Concessionary.destroy_all
    Vehicle.destroy_all
#---thi-birthers    
    Concessionary.create! [
        { name:'ANABERTO FLORES MONIVE', telephone:'CROC 6241800534'},
        { name:'ARIES EDIFICACION', telephone:''},
        { name:'ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HERMANOS S.A.', telephone:''},
        { name:'ABISAID ROMERO HERNANDEZ', telephone:''},
        { name:'ANTONIO ABAROA', telephone:''},
        { name:'ABUNDIO AMADOR', telephone:''},
        { name:'ALEJANDRO RAMIREZ', telephone:''},
        { name:'ALUMINIO Y TABLAROCA', telephone:''},
        { name:'ACABADOS CONSTRUCTORES DE LA BAJA SA DE CV', telephone:''},
        { name:'ALBARO CESEÑA AGUNDEZ', telephone:''},
        { name:'ANDRES BALDERAS', telephone:''},
        { name:'ASADERO DON FRAN', telephone:''},
        { name:'ARCENIO MIRANDA', telephone:''},
        { name:'JESUS ELENA AGRAMON VALENZUELA', telephone:''},
        { name:'ARTURO URIBE CORONA', telephone:''},
        { name:'ANTONIO MARQUEZ', telephone:''},
        { name:'ASIA SA DE CV', telephone:''},
        { name:'AMIGO RENTA DE MOTOS', telephone:''},
        { name:'ALFA Y OMEGA PROFESIONAL', telephone:''},
        { name:'AYALA FERRETERA', telephone:''},
        { name:'AZUL  MADERO', telephone:''},
        { name:'BALDERAS LOPEZ DAVID', telephone:''},
        { name:'BEATRIZ OLMOS', telephone:''},
        { name:'BEATRIZ ELENA CESEÑA', telephone:''},
        { name:'BODEGA LIZARRAGA', telephone:''},
        { name:'CABO FUELS LAS TORRES', telephone:''},
        { name:'CABO VERDE SA DE CV', telephone:''},
        { name:'CAMIONES Y PIPAS DEL SUR', telephone:''},
        { name:'CARLOS ALBERTO MENDEZ CRUZ', telephone:'CROC'},
        { name:'CALZAPATO', telephone:''},
        { name:'CDC LOS CABOS, SA DE CV', telephone:''},
        { name:'COSIO JOSE', telephone:''},
        { name:'CONTENEDORES ORTIZ', telephone:''},
        { name:'COMERCIAL LB', telephone:''},
        { name:'CONSTRUCTORES LIZARRAGA', telephone:''},
        { name:'CORNELIA SOTO', telephone:''},
        { name:'COMERCIAL NORTEAMERICANA', telephone:''},
        { name:'CLAUDIA ADRIANA MARTINEZ GONZALEZ', telephone:''},
        { name:'CRESCENCIO SORIANO REYES', telephone:''},
        { name:'CROC', telephone:''},
        { name:'COLONOS DEL PEDREGAL', telephone:''},
        { name:'CLUB CASCADAS DE BAJA', telephone:'6241174615 JESUS BARRERA'},
        { name:'DEMETRIO SANTANA FRANCO', telephone:''},
        { name:'DIESEL POWER', telephone:''},
        { name:'DOMINGO PEREZ ORTIZ', telephone:''},
        { name:'DIES CANERO', telephone:''},
        { name:'DISEÑOS Y CANTERA', telephone:''},
        { name:'ECO INOVA', telephone:'6241848824 JESUS MERLASCA'},
        { name:'EDGAR HUMBERTO PERALTA', telephone:''},
        { name:'ELIGIO COSIO AMADOR', telephone:'6241515670 ING.ENRIQUE MICHEL'},
        { name:'EQUIPOS Y MAQUINARIA', telephone:''},
        { name:'EL CALLEJON', telephone:''},
        { name:'FONATUR', telephone:''},
        { name:'FESTER', telephone:''},
        { name:'FRANCISCO SIMON FELIX', telephone:''},
        { name:'FRANCISCO ALBERTO AGUILAR', telephone:'CROC'},
        { name:'FYMSA', telephone:''},
        { name:'GEORGINA BALBOA', telephone:''},
        { name:'GERARDO FLORES', telephone:''},
        { name:'GINAX', telephone:''},
        { name:'GONZALO VEGA', telephone:''},
        { name:'GRUPO CONSTRUCTOR', telephone:''},
        { name:'HECTOR ROMERO HERNANDEZ', telephone:''},
        { name:'HECTOR CLAUDIO FAJARDO', telephone:''},
        { name:'HIELO CABO SAN LUCAS', telephone:''},
        { name:'HOMERO BARRANCO', telephone:''},
        { name:'HUMBERTO GARCIA', telephone:''},
        { name:'HOTEL PUEBLO BONITO', telephone:''},
        { name:'HOMEX', telephone:''},
        { name:'IGNACIO CESEÑA', telephone:''},
        { name:'IGNACIO FERNANDEZ', telephone:''},
        { name:'ISRAEL MEZA', telephone:''},
        { name:'JAVIER LIZARRAGA', telephone:''},
        { name:'JESUS ELENA AGRAMON VALENZUELA', telephone:''},
        { name:'JESUS RASCON', telephone:''},
        { name:'JESUS EDUARDO IBARRA', telephone:''},
        { name:'JUAN TORRES', telephone:''},
        { name:'JOSE ADAN CAMACHO', telephone:''},
        { name:'JUAN JOSE ORTIZ', telephone:''},
        { name:'JORGE FRANCISCO ROSALES', telephone:''},
        { name:'JOSE ALFREDO MENA', telephone:''},
        { name:'JOSE LUIS GONZALEZ', telephone:''},
        { name:'JOSE LUIS MONROY', telephone:''},
        { name:'JAIME RAMIREZ', telephone:''},
        { name:'JOSE MANUEL GARCIA', telephone:''},
        { name:'JOEL MORA MEZA', telephone:''},
        { name:'JOSE VICTOR', telephone:''},
        { name:'JOPE CONSTRUCTORES', telephone:''},
        { name:'JOVANI GERARDO', telephone:''},
        { name:'JUAN SANCHEZ CHICO', telephone:''},
        { name:'LUBRICANTES PENINSULARES', telephone:''},
        { name:'LUIS A. AGUILAR ALVAREZ', telephone:''},
        { name:'LUIS JAVIER SOTERO', telephone:''},
        { name:'LLANTERA ZAMORA', telephone:''},
        { name:'LOGISTICA Y TRANSPORTE ARNIAN', telephone:''},
        { name:'MADERERIA PICHONCHAS', telephone:''},
        { name:'MADERERIA CHICHUAHUA', telephone:''},
        { name:'MADERAS Y ACABADOS', telephone:''},
        { name:'MARIA DEL ROSARIO CESEÑA', telephone:''},
        { name:'MARIA DE LA CRUZ CASTRO', telephone:''},
        { name:'MANUEL JUAREZ', telephone:''},
        { name:'MARCOS ANGELES', telephone:''},
        { name:'MARCOS RIOS LLAMAS', telephone:''},
        { name:'MIGUEL VALDERAS', telephone:''},
        { name:'OMAR LOPEZ', telephone:''},
        { name:'PABLO GARCIA', telephone:''},
        { name:'PASA', telephone:''},
        { name:'PEDRO GARCIA FABIAN', telephone:'6241646457'},
        { name:'PABLO RAMIREZ', telephone:''},
        { name:'PEDRO TORRES ADAME', telephone:'6241179694'},
        { name:'PINTURAS PRISA', telephone:''},
        { name:'PINAL BIENES Y RAICES', telephone:''},
        { name:'PIPAS Y CAMIONES EL SUR', telephone:'APOYO'},
        { name:'PROCESA DE MEXICO', telephone:''},
        { name:'ROBERTO RANGEL', telephone:''},
        { name:'RAFAEL PAEZ', telephone:''},
        { name:'RECOGE BIEN', telephone:''},
        { name:'RICARDO GARCIA', telephone:''},
        { name:'RODOLFO MESA', telephone:'APOYO'},
        { name:'ROBERTO TOMYN SON', telephone:''},
        { name:'SANTOS CESEÑA', telephone:''},
        { name:'SERGIO SANTOS SALAS', telephone:''},
        { name:'SALVADOR RAMIREZ', telephone:''},
        { name:'SERVICIO TRANSPENINSULAR', telephone:''},
        { name:'SERVICIO DE TRANSPORTE SA DE CV', telephone:''},
        { name:'SERGIO AVILEZ', telephone:''},
        { name:'URETRABA', telephone:''},
        { name:'VICTOR MURO', telephone:''},
        { name:'VICTOR HUGO CESEÑA', telephone:''},
        { name:'VIDRIERA GUADALAJARA', telephone:''},
        { name:'VIDRIERA SAN MARCOS', telephone:''},
        { name:'VITROCAR SA DE CV', telephone:''},
        { name:'VIVEROS CAROLINA', telephone:''},
        { name:'VISION ECOLOGICA', telephone:''},
        { name:'WILLIAM R. SORIANO NAVA', telephone:''},
        { name:'COLONOS DEL PEDREGAL', telephone:''},
        { name:'CLUB CASCADAS DE BAJA', telephone:'6241174615 JESUS BARRERA'},
        { name:'DEMETRIO SANTANA FRANCO', telephone:''},
        { name:'DIESEL POWER', telephone:''},
        { name:'DOMINGO PEREZ ORTIZ', telephone:''},
        { name:'DIES CANERO', telephone:''},
        { name:'DISEÑOS Y CANTERA', telephone:''},
        { name:'ECO INOVA', telephone:'6241848824 JESUS MERLASCA'},
        { name:'EDGAR HUMBERTO PERALTA', telephone:''},
        { name:'ELIGIO COSIO AMADOR', telephone:'6241515670 ING.ENRIQUE MICHEL'},
        { name:'EQUIPOS Y MAQUINARIA', telephone:''},
        { name:'EL CALLEJON', telephone:''},
        { name:'FONATUR', telephone:''},
        { name:'FESTER', telephone:''},
        { name:'FRANCISCO SIMON FELIX', telephone:''},
        { name:'FRANCISCO ALBERTO AGUILAR', telephone:'CROC'},
        { name:'FYMSA', telephone:''},
        { name:'GEORGINA BALBOA', telephone:''},
        { name:'GERARDO FLORES', telephone:''},
        { name:'GINAX', telephone:''},
        { name:'GONZALO VEGA', telephone:''},
        { name:'GRUPO CONSTRUCTOR', telephone:''},
        { name:'HECTOR ROMERO HERNANDEZ', telephone:''},
        { name:'HECTOR CLAUDIO FAJARDO', telephone:''},
        { name:'HIELO CABO SAN LUCAS', telephone:''},
        { name:'HOMERO BARRANCO', telephone:''},
        { name:'HUMBERTO GARCIA', telephone:''},
        { name:'HOTEL PUEBLO BONITO', telephone:''},
        { name:'HOMEX', telephone:''},
        { name:'IGNACIO CESEÑA', telephone:''},
        { name:'IGNACIO FERNANDEZ', telephone:''},
        { name:'ISRAEL MEZA', telephone:''},
        { name:'JAVIER LIZARRAGA', telephone:''},
        { name:'JESUS ELENA AGRAMON VALENZUELA', telephone:''},
        { name:'JESUS RASCON', telephone:''},
        { name:'JESUS EDUARDO IBARRA', telephone:''},
        { name:'JUAN TORRES', telephone:''},
        { name:'JOSE ADAN CAMACHO', telephone:''},
        { name:'JUAN JOSE ORTIZ', telephone:''},
        { name:'JORGE FRANCISCO ROSALES', telephone:''},
        { name:'JOSE ALFREDO MENA', telephone:''},
        { name:'JOSE LUIS GONZALEZ', telephone:''},
        { name:'JOSE LUIS MONROY', telephone:''},
        { name:'JAIME RAMIREZ', telephone:''},
        { name:'JOSE MANUEL GARCIA', telephone:''},
        { name:'JOEL MORA MEZA', telephone:''},
        { name:'JOSE VICTOR', telephone:''},
        { name:'JOPE CONSTRUCTORES', telephone:''},
        { name:'JOVANI GERARDO', telephone:''},
        { name:'JUAN SANCHEZ CHICO', telephone:''},
        { name:'LUBRICANTES PENINSULARES', telephone:''},
        { name:'LUIS A. AGUILAR ALVAREZ', telephone:''},
        { name:'LUIS JAVIER SOTERO', telephone:''},
        { name:'LLANTERA ZAMORA', telephone:''},
        { name:'LOGISTICA Y TRANSPORTE ARNIAN', telephone:''},
        { name:'MADERERIA PICHONCHAS', telephone:''},
        { name:'MADERERIA CHICHUAHUA', telephone:''},
        { name:'MADERAS Y ACABADOS', telephone:''},
        { name:'MARIA DEL ROSARIO CESEÑA', telephone:''},
        { name:'MARIA DE LA CRUZ CASTRO', telephone:''},
        { name:'MANUEL JUAREZ', telephone:''},
        { name:'MARCOS ANGELES', telephone:''},
        { name:'MARCOS RIOS LLAMAS', telephone:''},
        { name:'MIGUEL VALDERAS', telephone:''},
        { name:'OMAR LOPEZ', telephone:''},
        { name:'PABLO GARCIA', telephone:''},
        { name:'PASA', telephone:''},
        { name:'PEDRO GARCIA FABIAN', telephone:'6241646457'},
        { name:'PABLO RAMIREZ', telephone:''},
        { name:'PEDRO TORRES ADAME', telephone:'6241179694'},
        { name:'PINTURAS PRISA', telephone:''},
        { name:'PINAL BIENES Y RAICES', telephone:''},
        { name:'PIPAS Y CAMIONES EL SUR', telephone:'APOYO'},
        { name:'PROCESA DE MEXICO', telephone:''},
        { name:'ROBERTO RANGEL', telephone:''},
        { name:'RAFAEL PAEZ', telephone:''},
        { name:'RECOGE BIEN', telephone:''},
        { name:'RICARDO GARCIA', telephone:''},
        { name:'RODOLFO MESA', telephone:'APOYO'},
        { name:'ROBERTO TOMYN SON', telephone:''},
        { name:'SANTOS CESEÑA', telephone:''},
        { name:'SERGIO SANTOS SALAS', telephone:''},
        { name:'SALVADOR RAMIREZ', telephone:''},
        { name:'SERVICIO TRANSPENINSULAR', telephone:''},
        { name:'SERVICIO DE TRANSPORTE SA DE CV', telephone:''},
        { name:'SERGIO AVILEZ', telephone:''},
        { name:'URETRABA', telephone:''},
        { name:'VICTOR MURO', telephone:''},
        { name:'VICTOR HUGO CESEÑA', telephone:''},
        { name:'VIDRIERA GUADALAJARA', telephone:''},
        { name:'VIDRIERA SAN MARCOS', telephone:''},
        { name:'VITROCAR SA DE CV', telephone:''},
        { name:'VIVEROS CAROLINA', telephone:''},
        { name:'VISION ECOLOGICA', telephone:''},
        { name:'WILLIAM R. SORIANO NAVA', telephone:''},
        { name:'CROC', telephone:''}
    ]
    Vehicle.create! [
        { plate:'2339ZNT', concessionary: Concessionary.find_by(name:'ANABERTO FLORES MONIVE')},
        { plate:'CE57124', concessionary: Concessionary.find_by(name:'ARIES EDIFICACION')},
        { plate:'CE62788', concessionary: Concessionary.find_by(name:'ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HERMANOS S.A.')},
        { plate:'ZMA479', concessionary: Concessionary.find_by(name:'ABISAID ROMERO HERNANDEZ')},
        { plate:'1634ZNT', concessionary: Concessionary.find_by(name:'ANTONIO ABAROA')},
        { plate:'6435ZNT', concessionary: Concessionary.find_by(name:'ABUNDIO AMADOR')},
        { plate:'1754ZNT', concessionary: Concessionary.find_by(name:'ALEJANDRO RAMIREZ')},
        { plate:'ZMY1543', concessionary: Concessionary.find_by(name:'ALUMINIO Y TABLAROCA')},
        { plate:'CE98488', concessionary: Concessionary.find_by(name:'ACABADOS CONSTRUCTORES DE LA BAJA SA DE CV')},
        { plate:'1601ZNT', concessionary: Concessionary.find_by(name:'ALBARO CESEÑA AGUNDEZ')},
        { plate:'1622ZNT', concessionary: Concessionary.find_by(name:'ANDRES BALDERAS')},
        { plate:'CE64647', concessionary: Concessionary.find_by(name:'ASADERO DON FRAN')},
        { plate:'1986ZNT', concessionary: Concessionary.find_by(name:'ARCENIO MIRANDA')},
        { plate:'1576ZNT', concessionary: Concessionary.find_by(name:'JESUS ELENA AGRAMON VALENZUELA')},
        { plate:'CE87612', concessionary: Concessionary.find_by(name:'ARTURO URIBE CORONA')},
        { plate:'2730ZNT', concessionary: Concessionary.find_by(name:'ANTONIO MARQUEZ')},
        { plate:'UD50996', concessionary: Concessionary.find_by(name:'ASIA SA DE CV')},
        { plate:'CE86894', concessionary: Concessionary.find_by(name:'AMIGO RENTA DE MOTOS')},
        { plate:'CE64351', concessionary: Concessionary.find_by(name:'ALFA Y OMEGA PROFESIONAL')},
        { plate:'CE57634', concessionary: Concessionary.find_by(name:'AYALA FERRETERA')},
        { plate:'CE87644', concessionary: Concessionary.find_by(name:'AZUL  MADERO')},
        { plate:'2312ZNT', concessionary: Concessionary.find_by(name:'BALDERAS LOPEZ DAVID')},
        { plate:'2187ZNT', concessionary: Concessionary.find_by(name:'BEATRIZ OLMOS')},
        { plate:'2461ZNT', concessionary: Concessionary.find_by(name:'BEATRIZ ELENA CESEÑA')},
        { plate:'CE86327', concessionary: Concessionary.find_by(name:'BODEGA LIZARRAGA')},
        { plate:'962XN2', concessionary: Concessionary.find_by(name:'CABO FUELS LAS TORRES')},
        { plate:'2810ZNT', concessionary: Concessionary.find_by(name:'CABO VERDE SA DE CV')},
        { plate:'1589ZNT', concessionary: Concessionary.find_by(name:'CAMIONES Y PIPAS DEL SUR')},
        { plate:'2330ZNT', concessionary: Concessionary.find_by(name:'CARLOS ALBERTO MENDEZ CRUZ')},
        { plate:'CE85913', concessionary: Concessionary.find_by(name:'CALZAPATO')},
        { plate:'CE86934', concessionary: Concessionary.find_by(name:'CDC LOS CABOS, SA DE CV')},
        { plate:'1587ZNT', concessionary: Concessionary.find_by(name:'COSIO JOSE')},
        { plate:'1960ZNT', concessionary: Concessionary.find_by(name:'CONTENEDORES ORTIZ')},
        { plate:'CE88762', concessionary: Concessionary.find_by(name:'COMERCIAL LB')},
        { plate:'2530ZNT', concessionary: Concessionary.find_by(name:'CONSTRUCTORES LIZARRAGA')},
        { plate:'2426ZNT', concessionary: Concessionary.find_by(name:'CORNELIA SOTO')},
        { plate:'CE5868', concessionary: Concessionary.find_by(name:'COMERCIAL NORTEAMERICANA')},
        { plate:'2357ZNT', concessionary: Concessionary.find_by(name:'CLAUDIA ADRIANA MARTINEZ GONZALEZ')},
        { plate:'3376ZNT', concessionary: Concessionary.find_by(name:'CRESCENCIO SORIANO REYES')},
        { plate:'2217ZNT',concessionary: Concessionary.find_by(name:'COLONOS DEL PEDREGAL')},
        { plate:'CE86166',concessionary: Concessionary.find_by(name:'CLUB CASCADAS DE BAJA')},
        { plate:'2290ZNT',concessionary: Concessionary.find_by(name:'DEMETRIO SANTANA FRANCO')},
        { plate:'CE63512',concessionary: Concessionary.find_by(name:'DIESEL POWER')},
        { plate:'CE00664',concessionary: Concessionary.find_by(name:'DOMINGO PEREZ ORTIZ')},
        { plate:'CE85824',concessionary: Concessionary.find_by(name:'DIES CANERO')},
        { plate:'CE85057',concessionary: Concessionary.find_by(name:'DISEÑOS Y CANTERA')},
        { plate:'3612ZNT',concessionary: Concessionary.find_by(name:'ECO INOVA')},
        { plate:'CE57725',concessionary: Concessionary.find_by(name:'EDGAR HUMBERTO PERALTA')},
        { plate:'1599ZNT',concessionary: Concessionary.find_by(name:'ELIGIO COSIO AMADOR')},
        { plate:'2515ZNT',concessionary: Concessionary.find_by(name:'EQUIPOS Y MAQUINARIA')},
        { plate:'CF08306',concessionary: Concessionary.find_by(name:'EL CALLEJON')},
        { plate:'78343',concessionary: Concessionary.find_by(name:'FONATUR')},
        { plate:'CE63578',concessionary: Concessionary.find_by(name:'FESTER')},
        { plate:'ZMY3295',concessionary: Concessionary.find_by(name:'FRANCISCO SIMON FELIX')},
        { plate:'1953ZNT',concessionary: Concessionary.find_by(name:'FRANCISCO ALBERTO AGUILAR')},
        { plate:'CE66054',concessionary: Concessionary.find_by(name:'FYMSA')},
        { plate:'2217ZNT',concessionary: Concessionary.find_by(name:'GEORGINA BALBOA')},
        { plate:'CE08272',concessionary: Concessionary.find_by(name:'GERARDO FLORES')},
        { plate:'CE58145',concessionary: Concessionary.find_by(name:'GINAX')},
        { plate:'CE87644',concessionary: Concessionary.find_by(name:'GONZALO VEGA')},
        { plate:'CE57124',concessionary: Concessionary.find_by(name:'GRUPO CONSTRUCTOR')},
        { plate:'22616 ONAPAFFA',concessionary: Concessionary.find_by(name:'HECTOR ROMERO HERNANDEZ')},
        { plate:'ZMA433N',concessionary: Concessionary.find_by(name:'HECTOR CLAUDIO FAJARDO')},
        { plate:'ZMN9227',concessionary: Concessionary.find_by(name:'HIELO CABO SAN LUCAS')},
        { plate:'2357ZNT',concessionary: Concessionary.find_by(name:'HOMERO BARRANCO')},
        { plate:'1709ZNT',concessionary: Concessionary.find_by(name:'HUMBERTO GARCIA')},
        { plate:'CE62038',concessionary: Concessionary.find_by(name:'HOTEL PUEBLO BONITO')},
        { plate:'VE6208',concessionary: Concessionary.find_by(name:'HOMEX')},
        { plate:'2258ZNT',concessionary: Concessionary.find_by(name:'IGNACIO CESEÑA')},
        { plate:'60137 ONAPAFFA',concessionary: Concessionary.find_by(name:'IGNACIO FERNANDEZ')},
        { plate:'2404ZNT',concessionary: Concessionary.find_by(name:'ISRAEL MEZA')},
        { plate:'2530ZNT',concessionary: Concessionary.find_by(name:'JAVIER LIZARRAGA')},
        { plate:'1576ZNT',concessionary: Concessionary.find_by(name:'JESUS ELENA AGRAMON VALENZUELA')},
        { plate:'2493ZNT',concessionary: Concessionary.find_by(name:'JESUS RASCON')},
        { plate:'JR73661',concessionary: Concessionary.find_by(name:'JESUS EDUARDO IBARRA')},
        { plate:'1829ZNT',concessionary: Concessionary.find_by(name:'JUAN TORRES')},
        { plate:'1718ZNT',concessionary: Concessionary.find_by(name:'JOSE ADAN CAMACHO')},
        { plate:'2028ZNT',concessionary: Concessionary.find_by(name:'JUAN JOSE ORTIZ')},
        { plate:'2664ZNT',concessionary: Concessionary.find_by(name:'JORGE FRANCISCO ROSALES')},
        { plate:'2810ZNT',concessionary: Concessionary.find_by(name:'JOSE ALFREDO MENA')},
        { plate:'28520',concessionary: Concessionary.find_by(name:'JOSE LUIS GONZALEZ')},
        { plate:'ZMW5872',concessionary: Concessionary.find_by(name:'JOSE LUIS MONROY')},
        { plate:'1734ZNT',concessionary: Concessionary.find_by(name:'JAIME RAMIREZ')},
        { plate:'1640ZNT',concessionary: Concessionary.find_by(name:'JOSE MANUEL GARCIA')},
        { plate:'2252ZNT',concessionary: Concessionary.find_by(name:'JOEL MORA MEZA')},
        { plate:'ZMA120F',concessionary: Concessionary.find_by(name:'JOSE VICTOR')},
        { plate:'CE82863',concessionary: Concessionary.find_by(name:'JOPE CONSTRUCTORES')},
        { plate:'2844ZNT',concessionary: Concessionary.find_by(name:'JOVANI GERARDO')},
        { plate:'1725ZNT',concessionary: Concessionary.find_by(name:'JUAN SANCHEZ CHICO')},
        { plate:'ZNA3997',concessionary: Concessionary.find_by(name:'LUBRICANTES PENINSULARES')},
        { plate:'2562ZNT',concessionary: Concessionary.find_by(name:'LUIS A. AGUILAR ALVAREZ')},
        { plate:'ZMX1096',concessionary: Concessionary.find_by(name:'LUIS JAVIER SOTERO')},
        { plate:'FU07113 ANAPROMEX',concessionary: Concessionary.find_by(name:'LLANTERA ZAMORA')},
        { plate:'CE87420',concessionary: Concessionary.find_by(name:'LOGISTICA Y TRANSPORTE ARNIAN')},
        { plate:'ZNA292R',concessionary: Concessionary.find_by(name:'MADERERIA PICHONCHAS')},
        { plate:'2187ZNT',concessionary: Concessionary.find_by(name:'MADERERIA CHICHUAHUA')},
        { plate:'CE08297',concessionary: Concessionary.find_by(name:'MADERAS Y ACABADOS')},
        { plate:'2730ZNT',concessionary: Concessionary.find_by(name:'MARIA DEL ROSARIO CESEÑA')},
        { plate:'2134ZNT',concessionary: Concessionary.find_by(name:'MARIA DE LA CRUZ CASTRO')},
        { plate:'ZMA240E',concessionary: Concessionary.find_by(name:'MANUEL JUAREZ')},
        { plate:'2312ZNT',concessionary: Concessionary.find_by(name:'MARCOS ANGELES')},
        { plate:'ZMY3745',concessionary: Concessionary.find_by(name:'MARCOS RIOS LLAMAS')},
        { plate:'2330ZNT',concessionary: Concessionary.find_by(name:'MIGUEL VALDERAS')},
      #  { plate:'',concessionary: Concessionary.find_by(name:'OMAR LOPEZ')},
        { plate:'1944ZNT',concessionary: Concessionary.find_by(name:'PABLO GARCIA')},
      #  { plate:'',concessionary: Concessionary.find_by(name:'PASA')},
        { plate:'1946ZNT',concessionary: Concessionary.find_by(name:'PEDRO GARCIA FABIAN')},
        { plate:'2404ZNT',concessionary: Concessionary.find_by(name:'PABLO RAMIREZ')},
        { plate:'1809ZNT',concessionary: Concessionary.find_by(name:'PEDRO TORRES ADAME')},
        { plate:' CE40252',concessionary: Concessionary.find_by(name:'PINTURAS PRISA')},
        { plate:'CE85859',concessionary: Concessionary.find_by(name:'PINAL BIENES Y RAICES')},
        { plate:'1589ZNT',concessionary: Concessionary.find_by(name:'PIPAS Y CAMIONES EL SUR')},
        { plate:'7960 C',concessionary: Concessionary.find_by(name:'PROCESA DE MEXICO')},
        { plate:'2418ZNT',concessionary: Concessionary.find_by(name:'ROBERTO RANGEL')},
        { plate:'CE62944',concessionary: Concessionary.find_by(name:'RAFAEL PAEZ')},
       # { plate:'',concessionary: Concessionary.find_by(name:'RECOGE BIEN')},
        { plate:'CE86053',concessionary: Concessionary.find_by(name:'RICARDO GARCIA')},
        { plate:'1695ZNT',concessionary: Concessionary.find_by(name:'RODOLFO MESA')},
        { plate:'ZMA546-P',concessionary: Concessionary.find_by(name:'ROBERTO TOMYN SON')},
        { plate:'2256ZNT',concessionary: Concessionary.find_by(name:'SANTOS CESEÑA')},
        { plate:'2304ZNT',concessionary: Concessionary.find_by(name:'SERGIO SANTOS SALAS')},
        { plate:'ZMW5848',concessionary: Concessionary.find_by(name:'SALVADOR RAMIREZ')},
        { plate:'4325ZNT',concessionary: Concessionary.find_by(name:'SERVICIO TRANSPENINSULAR')},
       # { plate:'',concessionary: Concessionary.find_by(name:'SERVICIO DE TRANSPORTE SA DE CV')},
        { plate:'1663ZNT',concessionary: Concessionary.find_by(name:'SERGIO AVILEZ')},
        { plate:'5876ZNS',concessionary: Concessionary.find_by(name:'URETRABA')},
        { plate:'CE82789',concessionary: Concessionary.find_by(name:'VICTOR MURO')},
        { plate:'1625ZNT',concessionary: Concessionary.find_by(name:'VICTOR HUGO CESEÑA')},
        { plate:'CE86824',concessionary: Concessionary.find_by(name:'VIDRIERA GUADALAJARA')},
        { plate:'ZMX8548',concessionary: Concessionary.find_by(name:'VIDRIERA SAN MARCOS')},
        { plate:'JH61645',concessionary: Concessionary.find_by(name:'VITROCAR SA DE CV')},
        { plate:'ZMA674F',concessionary: Concessionary.find_by(name:'VIVEROS CAROLINA')},
        { plate:'8419ZNT',concessionary: Concessionary.find_by(name:'VISION ECOLOGICA')},
        { plate:'2809ZNT',concessionary: Concessionary.find_by(name:'WILLIAM R. SORIANO NAVA')},
        { plate:'2312ZNT',concessionary: Concessionary.find_by(name:'CROC')},
        { plate:'1654ZNT',concessionary: Concessionary.find_by(name:'CROC')},
        { plate:'2418ZNT',concessionary: Concessionary.find_by(name:'CROC')},
        { plate:'1653ZNT',concessionary: Concessionary.find_by(name:'CROC')}

    ]